// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzdfuueNLi5TkeQ9s7odsigRg8J_8lFU',
    appId: '1:985365100623:web:5c52c11a22598033dad23a',
    messagingSenderId: '985365100623',
    projectId: 'habluquiz',
    authDomain: 'habluquiz.firebaseapp.com',
    storageBucket: 'habluquiz.firebasestorage.app',
    measurementId: 'G-VHTZN8KX04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSURGoauIGHT90s4157-0xryE2lgppw8',
    appId: '1:985365100623:android:dad9bb0cbaf81c66dad23a',
    messagingSenderId: '985365100623',
    projectId: 'habluquiz',
    storageBucket: 'habluquiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_A-eH4RaSl5imHdYItOXBoviSaTvf06c',
    appId: '1:985365100623:ios:ece9cf249426c92adad23a',
    messagingSenderId: '985365100623',
    projectId: 'habluquiz',
    storageBucket: 'habluquiz.firebasestorage.app',
    iosBundleId: 'com.example.habluQuiz',
  );
}
