class AppStrings {
  static const Map<String, String> _bnMonths = {
    'January': 'জানুয়ারি',
    'February': 'ফেব্রুয়ারি',
    'March': 'মার্চ',
    'April': 'এপ্রিল',
    'May': 'মে',
    'June': 'জুন',
    'July': 'জুলাই',
    'August': 'আগস্ট',
    'September': 'সেপ্টেম্বর',
    'October': 'অক্টোবর',
    'November': 'নভেম্বর',
    'December': 'ডিসেম্বর',
    'Jan': 'জানু',
    'Feb': 'ফেব্রু',
    'Mar': 'মার্চ',
    'Apr': 'এপ্রিল',
    'Jun': 'জুন',
    'Jul': 'জুলাই',
    'Aug': 'আগস্ট',
    'Sep': 'সেপ্টে',
    'Oct': 'অক্টো',
    'Nov': 'নভে',
    'Dec': 'ডিসে',
    'Total': 'সর্বমোট',
    'Overall': 'সর্বমোট',
    'This Month': 'চলতি মাস',
  };

  static String formatMonth(String month, {String lang = 'en'}) {
    if (lang == 'bn') {
      return _bnMonths[month] ?? month;
    }
    return month;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Nav
      'nav_home': 'Home',
      'nav_batch': 'Batch',
      'nav_students': 'Students',
      'nav_account': 'Account',
      'nav_settings': 'Settings',

      // General
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'close': 'Close',
      'search': 'Search',
      'sync': 'Sync',
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'required': 'Required',
      'optional': 'Optional',
      'add': 'Add',
      'update': 'Update',
      'call': 'Call',
      'na': 'N/A',

      // Home Screen
      'dashboard_title': 'Tuition Dashboard',
      'dashboard_subtitle': 'Overview & Quick Management',
      'hello_tutor': 'Hello',
      'have_great_day': 'Have a great day ahead!',
      'tutor_offline': 'Offline Tutor',
      'students_card_title': 'Students',
      'students_card_subtitle': '%d registered',
      'batches_card_title': 'Batches',
      'batches_card_subtitle': '%d active',
      'month_due_title': '%s Due',
      'total_due_title': 'Total Due',
      'this_month_paid_title': 'This Month Paid',
      'month_paid_title': '%s Paid',
      'overall_paid_title': 'Overall Paid',
      'recent_paid_fees': 'Recent Paid Fees',
      'recent_due_fees': 'Recent Due Fees',
      'view_all': 'View All',
      'no_fees_collected_yet': 'No fees collected yet',
      'no_fees_currently_due': 'No fees currently due',
      'student_id_prefix': 'Student ID: %s',
      'status_paid': 'Paid',
      'status_due': 'Due',

      // Batch Screen
      'batches_title': 'Batches',
      'sync_batches_tooltip': 'Sync Batches',
      'create_new_batch': 'Create New Batch',
      'batch_name_label': 'Batch Name *',
      'batch_name_hint': 'e.g., Class 10 - Science',
      'edit_batch_title': 'Edit Batch Name',
      'delete_batch_title': 'Delete Batch',
      'delete_batch_msg': 'Are you sure you want to delete this batch? Assigned students will become unbatched.',
      'save_batch': 'Save Batch',
      'no_batches_title': 'No Batches Available',
      'no_batches_subtitle': 'Create a batch to start organizing your students.',
      'create_first_batch': 'Create First Batch',
      'batches_synced': 'Batches synced successfully',
      'assign_month': 'Assign Month Fee',
      'enrolled_students': '%d enrolled students',
      'total_batches_stat': 'Batches',
      'total_students_stat': 'Students',
      'students_in_batch': 'Students in Batch',
      'no_students_in_batch': 'No students enrolled in this batch yet.',

      // Student Screen
      'students_title': 'Students',
      'sync_students_tooltip': 'Sync Students',
      'students_list_updated': 'Students list updated',
      'search_student_hint': 'Search student, ID, phone...',
      'all_batches': 'All Batches',
      'no_students_found': 'No Students Found',
      'no_students_subtitle': 'Add your first student to get started.',
      'add_new_student': 'Add New Student',
      'edit_student_details': 'Edit Student Details',
      'student_name_label': 'Student Name *',
      'student_class_label': 'Class *',
      'phone_number_optional': 'Phone Number (Optional)',
      'monthly_fee_label': 'Monthly Fee',
      'assign_batch_label': 'Assign Batch *',
      'select_batch_hint': 'Select a batch',
      'delete_student_title': 'Delete Student',
      'delete_student_msg': 'Are you sure you want to delete this student? All payment records for this student will remain safely stored.',
      'fill_required_fields': 'Please fill all required fields (Name, Class, Fee, Batch)',
      'valid_fee_error': 'Please enter a valid monthly fee number',
      'class_prefix': 'Class: %s',
      'batch_prefix': 'Batch: %s',
      'no_phone': 'No phone',
      'student_added_success': 'Student %s added successfully',
      'student_updated_success': 'Student %s updated successfully',
      'student_deleted_success': 'Student deleted successfully',

      // Account Screen
      'account_title': 'Student Ledger & Accounts',
      'account_subtitle': 'Search student by ID or name to view detailed billing history',
      'sync_accounts_tooltip': 'Sync Accounts',
      'account_records_updated': 'Account records updated',
      'total_collected': 'Total Collected',
      'total_pending': 'Total Pending',
      'search_account_hint': 'Enter student ID (e.g. 26001) or name...',
      'found_matching_students': 'Found %d matching students. Tap to open:',
      'quick_select_prompt': 'Select a student to inspect account ledger:',
      'all_students': 'All Students',
      'payment_history': 'Monthly Payment Records',
      'filter_all': 'All',
      'filter_pending': 'Pending',
      'filter_paid': 'Paid',
      'mark_paid': 'Mark as Paid',
      'cancel_payment': 'Cancel Payment',
      'cancel_fee_title': 'Cancel Fee Collection',
      'cancel_fee_msg': 'Are you sure you want to cancel the collected fee of %s for %s?\n\nThis will mark the payment as Pending Due.',
      'keep_paid': 'Keep Paid',
      'reset_to_pending': 'Yes, Reset to Pending',
      'payment_reset_msg': 'Payment for %s has been reset to Pending',
      'collect_fee_title': 'Collect Tuition Fee',
      'select_month_to_pay': 'Select month to collect fee for:',
      'amount_to_collect': 'Amount to Collect (%s)',
      'confirm_collection': 'Confirm & Mark Paid',
      'fee_collected_success': 'Fee collected successfully for %s',
      'no_unpaid_months': 'No unpaid months available for this student',
      'no_records_for_student': 'No fee records found for this student.',
      'no_student_found_title': 'No Student Found',
      'no_student_found_desc': 'No matching student found. Please check student ID or name.',
      'monthly_billed': 'Monthly Fee:',
      'total_billed_label': 'Total Billed:',
      'collected_label': 'Collected:',
      'pending_label': 'Pending Due:',
      'unpaid_months_count': 'Unpaid Months: %d',
      'all_dues_cleared': 'All dues cleared! Great job! 🎉',

      // Dialogs
      'due_students_dialog_title': '%s Due Students',
      'paid_students_dialog_title': '%s Paid Students',
      'no_due_students_msg': 'No dues found for this period! 🎉',
      'no_paid_students_msg': 'No paid records found for this period.',
      'roll_id_prefix': 'Roll / ID: %s',
      'call_student': 'Call',

      // Settings Screen
      'settings_title': 'Settings',
      'settings_subtitle': 'Storage, Cloud Backup & Preferences',
      'offline_mode': 'Local Offline Mode',
      'firebase_connected': 'Firebase Connected',
      'signin_google': 'Sign in with Google to Sync',
      'sign_out': 'Sign Out',
      'confirm_signout_title': 'Confirm Logout',
      'confirm_signout_msg': 'Are you sure you want to sign out? Your local data will remain safe on your device.',
      'storage_sync_title': 'Data Storage & Firebase Sync',
      'storage_sync_desc': 'Your tuition data is stored locally (Hive) for instant offline speed. Connect to Firebase for cloud backups.',
      'auto_sync': 'Auto-Sync Changes',
      'auto_sync_desc': 'Automatically update Firebase when changes are made',
      'last_cloud_sync': 'Last Cloud Sync:',
      'backup_cloud_btn': 'Backup to Cloud',
      'restore_data_btn': 'Restore Data',
      'local_stats_title': 'Local Storage Statistics',
      'preferences_title': 'Preferences & Maintenance',
      'currency_symbol': 'Currency Symbol',
      'app_language': 'App Language',
      'language_english': 'English',
      'language_bengali': 'বাংলা (Bangla)',
      'clear_local_data': 'Clear Local Data',
      'clear_local_data_desc': 'Removes local device database entries',
      'confirm_clear_title': 'Clear Local Database',
      'confirm_clear_msg': 'Are you sure you want to clear local data from this device? If backed up to Firebase, you can restore anytime.',
      'about_app': 'About Application',
      'app_name_label': 'Application Name',
      'app_name_value': 'Tuition Fee Manager',
      'app_version_label': 'Version',
      'offline_support_label': 'Offline Support',
      'offline_support_val': 'Enabled (Hive Engine)',
      'cloud_db_label': 'Cloud Database',
      'cloud_db_val': 'Firebase Cloud Firestore',

      // Subscription & Plans
      'subscription_section_title': 'Subscription & Plans',
      'active_plan': 'Active Plan',
      'upgrade_plan': 'Upgrade Plan',
      'free_tier_status': 'Free Tier (Up to 5 batches & 10 students)',
      'batches_limit_status': 'Batches: %d / %s',
      'students_limit_status': 'Students: %d / %s',
      'plan_limit_reached_title': 'Subscription Plan Limit Reached',
      'batch_limit_msg': 'You have reached the maximum allowed batches for your current plan. Please upgrade your plan from our website to create more batches.',
      'student_limit_msg': 'You have reached the maximum allowed students for your current plan. Please upgrade your plan from our website to add more students.',
      'view_plans_website': 'Purchase on Website',
      'enter_activation_code': 'Enter Activation Code',
      'activation_code_hint': 'e.g., TF-PRO-3M-XXXX',
      'activate_btn': 'Activate Plan',
      'invalid_code_msg': 'Invalid or unrecognized activation code. Please check your purchase confirmation.',
      'code_activated_success': 'Subscription successfully activated!',
      'plan_valid_until': 'Valid until: %s',
      'unlimited': 'Unlimited',

      // Google Sign In Play Store error
      'google_signin_error_title': 'Google Play Signing Configuration Required',
      'google_signin_error_desc': 'Google Play requires the Play App Signing SHA-1 fingerprint to be added to Firebase Console under Project Settings -> Android App. Local offline mode is active and fully functional.',
    },
    'bn': {
      // Nav
      'nav_home': 'হোম',
      'nav_batch': 'ব্যাচ',
      'nav_students': 'শিক্ষার্থী',
      'nav_account': 'হিসাব',
      'nav_settings': 'সেটিংস',

      // General
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
      'edit': 'সম্পাদনা',
      'delete': 'মুছে ফেলুন',
      'confirm': 'নিশ্চিত করুন',
      'close': 'বন্ধ করুন',
      'search': 'অনুসন্ধান',
      'sync': 'সিঙ্ক করুন',
      'success': 'সফল',
      'error': 'ত্রুটি',
      'warning': 'সতর্কতা',
      'required': 'প্রয়োজনীয়',
      'optional': 'ঐচ্ছিক',
      'add': 'যোগ করুন',
      'update': 'আপডেট',
      'call': 'কল দিন',
      'na': 'প্রযোজ্য নয়',

      // Home Screen
      'dashboard_title': 'টিউশন ড্যাশবোর্ড',
      'dashboard_subtitle': 'সামগ্রিক চিত্র ও দ্রুত ব্যবস্থাপনা',
      'hello_tutor': 'স্বাগতম',
      'have_great_day': 'আপনার দিনটি শুভ হোক!',
      'tutor_offline': 'গৃহশিক্ষক (অফলাইন মোড)',
      'students_card_title': 'শিক্ষার্থী',
      'students_card_subtitle': '%d জন নিবন্ধিত',
      'batches_card_title': 'ব্যাচসমূহ',
      'batches_card_subtitle': '%d টি সক্রিয়',
      'month_due_title': '%s বকেয়া',
      'total_due_title': 'মোট বকেয়া',
      'this_month_paid_title': 'চলতি মাসে আদায়',
      'month_paid_title': '%s আদায়',
      'overall_paid_title': 'সর্বমোট আদায়',
      'recent_paid_fees': 'সাম্প্রতিক পরিশোধিত ফি',
      'recent_due_fees': 'সাম্প্রতিক বকেয়া ফি',
      'view_all': 'সব দেখুন',
      'no_fees_collected_yet': 'এখনো কোনো ফি আদায় হয়নি',
      'no_fees_currently_due': 'বর্তমানে কোনো ফি বকেয়া নেই',
      'student_id_prefix': 'শিক্ষার্থী আইডি: %s',
      'status_paid': 'পরিশোধিত',
      'status_due': 'বকেয়া',

      // Batch Screen
      'batches_title': 'ব্যাচসমূহ',
      'sync_batches_tooltip': 'ব্যাচ সিঙ্ক করুন',
      'create_new_batch': 'নতুন ব্যাচ তৈরি করুন',
      'batch_name_label': 'ব্যাচের নাম *',
      'batch_name_hint': 'যেমন: ১০ম শ্রেণী - বিজ্ঞান',
      'edit_batch_title': 'ব্যাচের নাম পরিবর্তন',
      'delete_batch_title': 'ব্যাচ মুছে ফেলুন',
      'delete_batch_msg': 'আপনি কি এই ব্যাচটি মুছে ফেলতে চান? এতে থাকা শিক্ষার্থীরা ব্যাচহীন অবস্থায় সংরক্ষিত থাকবে।',
      'save_batch': 'ব্যাচ সেভ করুন',
      'no_batches_title': 'কোনো ব্যাচ তৈরি করা হয়নি',
      'no_batches_subtitle': 'শিক্ষার্থীদের সাজাতে এখনই একটি ব্যাচ তৈরি করুন।',
      'create_first_batch': 'প্রথম ব্যাচ তৈরি করুন',
      'batches_synced': 'ব্যাচের তথ্য সফলভাবে সিঙ্ক হয়েছে',
      'assign_month': 'মাসের ফি নির্ধারণ করুন',
      'enrolled_students': '%d জন শিক্ষার্থী',
      'total_batches_stat': 'ব্যাচ',
      'total_students_stat': 'শিক্ষার্থী',
      'students_in_batch': 'ব্যাচের শিক্ষার্থীরা',
      'no_students_in_batch': 'এই ব্যাচে এখনো কোনো শিক্ষার্থী নেই।',

      // Student Screen
      'students_title': 'শিক্ষার্থীবৃন্দ',
      'sync_students_tooltip': 'শিক্ষার্থী সিঙ্ক করুন',
      'students_list_updated': 'শিক্ষার্থীদের তালিকা আপডেট হয়েছে',
      'search_student_hint': 'নাম, আইডি বা ফোন নম্বর লিখুন...',
      'all_batches': 'সকল ব্যাচ',
      'no_students_found': 'কোনো শিক্ষার্থী পাওয়া যায়নি',
      'no_students_subtitle': 'নতুন শিক্ষার্থী যুক্ত করতে নিচের বাটনে চাপুন।',
      'add_new_student': 'নতুন শিক্ষার্থী যোগ করুন',
      'edit_student_details': 'শিক্ষার্থীর তথ্য পরিবর্তন',
      'student_name_label': 'শিক্ষার্থীর নাম *',
      'student_class_label': 'শ্রেণী *',
      'phone_number_optional': 'ফোন নম্বর (ঐচ্ছিক)',
      'monthly_fee_label': 'মাসিক ফি',
      'assign_batch_label': 'ব্যাচ নির্বাচন *',
      'select_batch_hint': 'একটি ব্যাচ নির্বাচন করুন',
      'delete_student_title': 'শিক্ষার্থী মুছে ফেলুন',
      'delete_student_msg': 'আপনি কি এই শিক্ষার্থীকে মুছে ফেলতে চান? তার পূর্ববর্তী পেমেন্ট রেকর্ড সুরক্ষিত থাকবে।',
      'fill_required_fields': 'অনুগ্রহ করে সকল প্রয়োজনীয় তথ্য পূরণ করুন (নাম, শ্রেণী, ফি, ব্যাচ)',
      'valid_fee_error': 'অনুগ্রহ করে সঠিক মাসিক ফি সংখ্যা লিখুন',
      'class_prefix': 'শ্রেণী: %s',
      'batch_prefix': 'ব্যাচ: %s',
      'no_phone': 'ফোন নম্বর নেই',
      'student_added_success': 'শিক্ষার্থী %s সফলভাবে যুক্ত হয়েছে',
      'student_updated_success': 'শিক্ষার্থী %s সফলভাবে আপডেট হয়েছে',
      'student_deleted_success': 'শিক্ষার্থী সফলভাবে মুছে ফেলা হয়েছে',

      // Account Screen
      'account_title': 'শিক্ষার্থীদের হিসাব ও লেজার',
      'account_subtitle': 'শিক্ষার্থীর আইডি বা নাম লিখে তার সম্পূর্ণ পেমেন্ট বিবরণ দেখুন',
      'sync_accounts_tooltip': 'হিসাব সিঙ্ক করুন',
      'account_records_updated': 'হিসাবের তথ্য সফলভাবে আপডেট হয়েছে',
      'total_collected': 'মোট আদায়',
      'total_pending': 'মোট বকেয়া',
      'search_account_hint': 'আইডি (যেমন ২৬০০১) বা নাম লিখুন...',
      'found_matching_students': '%d জন শিক্ষার্থী পাওয়া গেছে। নির্বাচন করতে চাপুন:',
      'quick_select_prompt': 'হিসাব ও লেজার দেখতে শিক্ষার্থী নির্বাচন করুন:',
      'all_students': 'সকল শিক্ষার্থী',
      'payment_history': 'মাসিক পেমেন্ট হিস্ট্রি',
      'filter_all': 'সকল',
      'filter_pending': 'বকেয়া',
      'filter_paid': 'পরিশোধিত',
      'mark_paid': 'পরিশোধ সম্পন্ন',
      'cancel_payment': 'পেমেন্ট বাতিল',
      'cancel_fee_title': 'ফি সংগ্রহ বাতিল',
      'cancel_fee_msg': 'আপনি কি %s ফি (মাস: %s) বাতিল করতে চান?\n\nএটি পুনরায় বকেয়া হিসেবে চিহ্নিত হবে।',
      'keep_paid': 'পরিশোধিত রাখুন',
      'reset_to_pending': 'হ্যাঁ, বকেয়া চিহ্নিত করুন',
      'payment_reset_msg': '%s মাসের পেমেন্ট বকেয়া হিসেবে চিহ্নিত করা হয়েছে',
      'collect_fee_title': 'টিউশন ফি গ্রহণ',
      'select_month_to_pay': 'যে মাসের ফি নিচ্ছেন নির্বাচন করুন:',
      'amount_to_collect': 'গৃহীত টাকার পরিমাণ (%s)',
      'confirm_collection': 'নিশ্চিত করুন ও পেইড চিহ্নিত করুন',
      'fee_collected_success': '%s মাসের ফি সফলভাবে গ্রহণ করা হয়েছে',
      'no_unpaid_months': 'এই শিক্ষার্থীর কোনো বকেয়া মাস নেই',
      'no_records_for_student': 'এই শিক্ষার্থীর কোনো ফি রেকর্ড পাওয়া যায়নি।',
      'no_student_found_title': 'কোনো শিক্ষার্থী পাওয়া যায়নি',
      'no_student_found_desc': 'প্রদত্ত তথ্য অনুযায়ী কোনো শিক্ষার্থী পাওয়া যায়নি। আইডি বা নাম পরীক্ষা করুন।',
      'monthly_billed': 'মাসিক ফি:',
      'total_billed_label': 'মোট ধার্য:',
      'collected_label': 'মোট আদায়:',
      'pending_label': 'মোট বকেয়া:',
      'unpaid_months_count': 'বকেয়া মাস: %dটি',
      'all_dues_cleared': 'সকল বকেয়া পরিশোধিত! চমৎকার! 🎉',

      // Dialogs
      'due_students_dialog_title': '%s বকেয়া শিক্ষার্থী তালিকা',
      'paid_students_dialog_title': '%s পরিশোধিত শিক্ষার্থী তালিকা',
      'no_due_students_msg': 'এই সময়ে কোনো শিক্ষার্থীর বকেয়া নেই! 🎉',
      'no_paid_students_msg': 'এই সময়ে কোনো পরিশোধের তথ্য পাওয়া যায়নি।',
      'roll_id_prefix': 'রোল / আইডি: %s',
      'call_student': 'কল দিন',

      // Settings Screen
      'settings_title': 'সেটিংস',
      'settings_subtitle': 'স্টোরেজ, ক্লাউড ব্যাকআপ এবং অ্যাপ পছন্দসমূহ',
      'offline_mode': 'লোকাল অফলাইন মোড',
      'firebase_connected': 'ফায়ারবেস সংযুক্ত',
      'signin_google': 'গুগল দিয়ে সাইন ইন করুন',
      'sign_out': 'সাইন আউট',
      'confirm_signout_title': 'সাইন আউট নিশ্চিত করুন',
      'confirm_signout_msg': 'আপনি কি সাইন আউট করতে চান? আপনার সব ডাটা এই মোবাইলে নিরাপদে থাকবে।',
      'storage_sync_title': 'ডাটা স্টোরেজ ও ফায়ারবেস ব্যাকআপ',
      'storage_sync_desc': 'আপনার অ্যাপের ডাটা সবসময় অফলাইনে আপনার ফোনে থাকে (হাইভ ইঞ্জিন)। অনলাইন ব্যাকআপের জন্য ফায়ারবেস যুক্ত করুন।',
      'auto_sync': 'অটো-সিঙ্ক ব্যাকআপ',
      'auto_sync_desc': 'তথ্য পরিবর্তন হলে নিজে থেকেই ফায়ারবেসে আপডেট হবে',
      'last_cloud_sync': 'সর্বশেষ ব্যাকআপ:',
      'backup_cloud_btn': 'ক্লাউডে ব্যাকআপ নিন',
      'restore_data_btn': 'ডাটা রিস্টোর করুন',
      'local_stats_title': 'লোকাল স্টোরেজ পরিসংখ্যান',
      'preferences_title': 'অ্যাপ পছন্দ ও রক্ষণাবেক্ষণ',
      'currency_symbol': 'মুদ্রা প্রতীক',
      'app_language': 'অ্যাপের ভাষা',
      'language_english': 'English',
      'language_bengali': 'বাংলা (Bangla)',
      'clear_local_data': 'লোকাল ডাটা পরিষ্কার করুন',
      'clear_local_data_desc': 'ফোনের ডাটাবেস সম্পূর্ণ খালি করবে',
      'confirm_clear_title': 'ডাটাবেস পরিষ্কার নিশ্চিতকরণ',
      'confirm_clear_msg': 'আপনি কি নিশ্চিত? ফায়ারবেসে ব্যাকআপ থাকলে আপনি পরে যেকোনো সময় রিস্টোর করতে পারবেন।',
      'about_app': 'অ্যাপ্লিকেশন সম্পর্কিত তথ্য',
      'app_name_label': 'অ্যাপ্লিকেশনের নাম',
      'app_name_value': 'টিউশন ফি ম্যানেজার',
      'app_version_label': 'ভার্সন',
      'offline_support_label': 'অফলাইন সুবিধা',
      'offline_support_val': 'চালু আছে (হাইভ ইঞ্জিন)',
      'cloud_db_label': 'ক্লাউড ডাটাবেস',
      'cloud_db_val': 'ফায়ারবেস ক্লাউড ফায়ারস্টোর',

      // Subscription & Plans
      'subscription_section_title': 'সাবস্ক্রিপশন ও প্ল্যান',
      'active_plan': 'বর্তমান প্ল্যান',
      'upgrade_plan': 'প্ল্যান আপগ্রেড করুন',
      'free_tier_status': 'ফ্রি প্ল্যান (সর্বোচ্চ ৫টি ব্যাচ ও ১০ জন শিক্ষার্থী)',
      'batches_limit_status': 'ব্যাচ সংখ্যা: %d / %s',
      'students_limit_status': 'শিক্ষার্থী সংখ্যা: %d / %s',
      'plan_limit_reached_title': 'প্ল্যানের সীমা পূর্ণ হয়েছে',
      'batch_limit_msg': 'আপনার বর্তমান প্ল্যানের ব্যাচ তৈরির সর্বোচ্চ সীমা শেষ হয়েছে। আরও ব্যাচ তৈরি করতে আমাদের ওয়েবসাইট থেকে প্ল্যান কিনুন।',
      'student_limit_msg': 'আপনার বর্তমান প্ল্যানের শিক্ষার্থী যোগ করার সর্বোচ্চ সীমা শেষ হয়েছে। আরও শিক্ষার্থী যুক্ত করতে আমাদের ওয়েবসাইট থেকে প্ল্যান কিনুন।',
      'view_plans_website': 'ওয়েবসাইটে প্ল্যান কিনুন',
      'enter_activation_code': 'অ্যাক্টিভেশন কোড দিন',
      'activation_code_hint': 'যেমন: TF-PRO-3M-XXXX',
      'activate_btn': 'প্ল্যান সক্রিয় করুন',
      'invalid_code_msg': 'অ্যাক্টিভেশন কোডটি সঠিক নয়। অনুগ্রহ করে ক্রয়ের রসিদ চেক করুন।',
      'code_activated_success': 'সাবস্ক্রিপশন প্ল্যান সফলভাবে সক্রিয় হয়েছে!',
      'plan_valid_until': 'মেয়াদ উত্তীর্ণের তারিখ: %s',
      'unlimited': 'সীমাহীন (আনলিমিটেড)',

      // Google Sign In Play Store error
      'google_signin_error_title': 'গুগল প্লে সাইনিং কনফিগারেশন প্রয়োজন',
      'google_signin_error_desc': 'গুগল প্লে স্টোর অ্যাপ সাইনিং SHA-1 ফিঙ্গারপ্রিন্ট ফায়ারবেস কনসোলে (Project Settings -> Android App) যোগ করতে হবে। বর্তমানে লোকাল অফলাইন মোড সম্পূর্ণ সচল ও কার্যকর আছে।',
    },
  };

  static String get(String key, {String lang = 'en'}) {
    final langMap = _localizedValues[lang] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}
